easy_admin:
    site_name: 'Aboubacar Sambare'
    entities:
        Project:
            class: App\Entity\Project
            list:
                fields:
                    - { property: 'name'}
                    - { property: 'imageFile' }
                    - {property: 'slug'}
                    - {property: 'description'}
                    - { property: 'image', type: 'image', base_path: '%app.path.portfolio_images%' }
                    - { property: 'link' }
            form:
                fields:
                    - { property: 'name'}
                    - {property: 'slug'}
                    - {property: 'description'}
                    - { property: 'imageFile', type: 'vich_image' }
                    - { property: 'link' }
            show:
                fields:
                    - { property: 'name'}
                    - {property: 'slug'}
                    - {property: 'description'}
                    - { property: 'image', type: 'image', base_path: '%%app.path.portfolio_images%' } 
                    - { property: 'link' }      
        User:
            class: App\Entity\User
            acme_project:
                export_path: '%kernel.project_dir/var/export/user'
                password_encoding: { algorithm: 'bcrypt', cost: 12 }
  # change the following to the namespaces of your own entities
